-- 코드를 작성해주세요
SELECT A.ID, COUNT(A.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS A LEFT JOIN ECOLI_DATA AS B ON A.ID = B.PARENT_ID
WHERE B.PARENT_ID IS NOT NULL # 부모가 없을 경우 ROOT이므로 제외
GROUP BY A.ID
ORDER BY A.ID;