-- 코드를 작성해주세요
WITH RECURSIVE GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT A.ID, A.PARENT_ID, GEN + 1 AS GEN
    FROM ECOLI_DATA AS A JOIN GENERATION AS B ON A.PARENT_ID = B.ID
)
SELECT COUNT(*) AS COUNT, GEN AS GENERATION
FROM GENERATION AS A
WHERE A.ID NOT IN (
    SELECT PARENT_ID AS ID
    FROM GENERATION AS B
    WHERE B.GEN = A.GEN + 1
    )
GROUP BY GENERATION
ORDER BY GENERATION