-- 코드를 작성해주세요
SELECT (
           CASE
               WHEN SKILL_CODE IN (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End')
                   AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
               WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
               WHEN SKILL_CODE IN (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C'
               END
           ) AS GRADE, ID, EMAIL
FROM DEVELOPERS
WHERE (
          SKILL_CODE IN (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End')
              OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
          )
ORDER BY GRADE, ID;
