-- 코드를 작성해주세요
SELECT II2.ITEM_ID, II2.ITEM_NAME, II2.RARITY
FROM (
         SELECT IT.ITEM_ID
         FROM ITEM_TREE AS IT LEFT JOIN ITEM_INFO AS II ON IT.PARENT_ITEM_ID = II.ITEM_ID
         WHERE II.RARITY = 'RARE') AS tmp,
     ITEM_INFO AS II2
WHERE II2.ITEM_ID = tmp.ITEM_ID
ORDER BY II2.ITEM_ID DESC;