-- 코드를 입력하세요
-- 내 풀이
SELECT DISTINCT A.CAR_ID, IF(B.CAR_ID IS NOT NULL, "대여중", "대여 가능") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
         LEFT JOIN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE) AS B
                   ON A.CAR_ID = B.CAR_ID
ORDER BY A.CAR_ID DESC;

-- GROUP BY로 풀이
SELECT CAR_ID,
       (CASE
            WHEN CAR_ID IN (SELECT CAR_ID
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                            WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE)
                THEN '대여중'
            ELSE '대여 가능'
           END) AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC