-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, FLOOR((A.DAILY_FEE * ((100 - C.DISCOUNT_RATE))/100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B,
     (
         SELECT CAR_TYPE, DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
         WHERE DURATION_TYPE LIKE "30%"
     ) AS C
WHERE A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = C.CAR_TYPE
  AND (A.CAR_TYPE = 'SUV' OR A.CAR_TYPE = '세단')
  AND (B.START_DATE IS NULL OR B.START_DATE > '2022-11-30' OR B.END_DATE < '2022-11-01')
  AND (A.DAILY_FEE * ((100 - C.DISCOUNT_RATE)/100)) * 30 >= 500000
  AND (A.DAILY_FEE * ((100 - C.DISCOUNT_RATE)/100)) * 30 < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID;