SELECT A.CAR_ID,
       A.CAR_TYPE,
       FLOOR((A.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
         INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
                    ON A.CAR_TYPE = D.CAR_TYPE
                        AND D.DURATION_TYPE LIKE '30%'
WHERE (A.CAR_TYPE = 'SUV' OR A.CAR_TYPE = '세단')
  AND (A.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) * 30 >= 500000
  AND (A.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) * 30 < 2000000
  AND NOT EXISTS (SELECT 1
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
                  WHERE A.CAR_ID = B.CAR_ID
                    AND B.START_DATE <= '2022-11-30'
                    AND B.END_DATE >= '2022-11-01')
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID;