SELECT TMP.CHILD_ID AS ID
FROM ECOLI_DATA AS A,
     (
         SELECT B.ID, B.PARENT_ID, C.ID AS CHILD_ID
         FROM ECOLI_DATA AS B, ECOLI_DATA AS C
         WHERE B.ID = C.PARENT_ID
     ) AS TMP
WHERE A.ID = TMP.PARENT_ID
  AND A.PARENT_ID IS NULL
ORDER BY TMP.CHILD_ID;