-- 코드를 작성해주세요
SELECT TMP.CHILD_ID AS ID
FROM ECOLI_DATA AS A LEFT JOIN
     (
         SELECT B.ID, B.PARENT_ID, C.ID AS CHILD_ID
         FROM ECOLI_DATA AS B LEFT JOIN ECOLI_DATA AS C ON B.ID = C.PARENT_ID
         WHERE C.PARENT_ID IS NOT NULL
     ) AS TMP
     ON A.ID = TMP.PARENT_ID
WHERE TMP.CHILD_ID IS NOT NULL AND A.PARENT_ID IS NULL
ORDER BY TMP.CHILD_ID;